
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "1.25",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "hyprlauncher"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function () 
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

hl.on("hyprland.start", function ()
    -- Status bar
    hl.exec_cmd("waybar")
    -- Notification daemon
    hl.exec_cmd("mako")
    -- Wallpaper (wrapper applies it over IPC; see script for why)
    hl.exec_cmd("$HOME/.config/hypr/scripts/wallpaper.sh")
    -- Idle management (dim / lock / dpms / suspend)
    hl.exec_cmd("hypridle")
    -- Polkit authentication agent (GUI password prompts)
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    -- Clipboard history
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    -- Keep clipboard contents alive after the source app closes (if installed)
    hl.exec_cmd("command -v wl-clip-persist >/dev/null && wl-clip-persist --clipboard regular")
    -- On-screen display for volume/brightness keys (if installed)
    hl.exec_cmd("command -v swayosd-server >/dev/null && swayosd-server")
    -- Load hyprpm plugins, then re-read the config so plugin options apply.
    -- Without the second step the hyprbars block below is skipped at boot,
    -- because hl.plugin.hyprbars does not exist yet when the config is parsed.
    hl.exec_cmd("command -v hyprpm >/dev/null && hyprpm reload -n && hyprctl reload")
end)


--------------------
---- AUTOMATION ----
--------------------

-- Silence notifications for as long as a screen share is running, so nothing
-- private pops into a call. The "silenced" notice is drawn by Hyprland itself
-- rather than mako, because mako is muted by then.
hl.on("screenshare.state", function(active, kind, name)
    if active then
        hl.dispatch(hl.dsp.exec_cmd("makoctl mode -a do-not-disturb"))
        hl.notification.create({
            text    = "Screen sharing - notifications silenced",
            timeout = 4000,
            icon    = "warning",
        })
    else
        hl.dispatch(hl.dsp.exec_cmd(
            "makoctl mode -r do-not-disturb && notify-send -u low 'Screen share ended' 'Notifications back on'"))
    end
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 2,
        gaps_out = 6,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled    = true,
            size       = 2,
            passes     = 2,
            special    = true,   -- blur the scratchpad too
            brightness = 0.60,
            contrast   = 0.75,
            vibrancy   = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Groupbar styling (Omarchy's). Matters now that SUPER + G groups windows:
-- the stock groupbar is a fat coloured strip.
hl.config({
    group = {
        col = {
            border_active          = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            border_inactive        = "rgba(595959aa)",
            border_locked_active   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            border_locked_inactive = "rgba(595959aa)",
        },

        groupbar = {
            font_size          = 12,
            font_family        = "monospace",
            font_weight_active = "ultraheavy",
            font_weight_inactive = "normal",

            indicator_height = 0,
            indicator_gap    = 5,
            height           = 22,
            gaps_in          = 5,
            gaps_out         = 0,

            text_color          = "rgb(ffffff)",
            text_color_inactive = "rgba(ffffff90)",
            col = {
                active   = "rgba(00000040)",
                inactive = "rgba(00000020)",
            },

            gradients                 = true,
            gradient_rounding         = 0,
            gradient_round_only_edges = false,
        },
    },

    cursor = {
        hide_on_key_press       = true,
        warp_on_change_workspace = 1,
    },

    binds = {
        -- Hide the scratchpad when switching away from it
        hide_special_on_workspace_change = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Smart gaps: a workspace holding a single tiled window gets no gaps, no
-- border and no rounding, so one window really does fill the screen.
-- w[tv1] = exactly one visible tiled window; f[1] = a fullscreen workspace.
hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })

-- Named project workspaces, each with sub-workspaces "<name>.N".
-- Entering "<name>.1" while empty opens one kitty per remote tmux session via
-- ~/.local/bin/r. Higher sub-workspaces start empty, as scratch space for that
-- project. No 'persistent' here: it would pre-create the workspace and suppress
-- on_created_empty.
local wsTerminals = "$HOME/.config/hypr/scripts/workspace-terminals.sh"
local wsSub       = "$HOME/.config/hypr/scripts/ws-sub.sh"

local projects = {
    { name = "alpha",            key = "O" },
    { name = "beta",       key = "V" },
    { name = "gamma",             key = "D" },
    { name = "delta",           key = "S" },
    { name = "epsilon",         key = "H" },
    { name = "zeta", key = "L" },
    { name = "eta",        key = "C" },
    { name = "theta",           key = "K" },
    { name = "iota",            key = "Q" },
    { name = "kappa",           key = "J" },
    { name = "lambda",          key = "E" },
}

for _, proj in ipairs(projects) do
    local n = proj.name
    hl.workspace_rule({
        workspace        = "name:" .. n .. ".1",
        on_created_empty = wsTerminals .. " " .. n .. " " .. n .. "1 " .. n .. "2",
    })
end
hl.window_rule({
    name  = "no-gaps-wtv1",
    match = { float = false, workspace = "w[tv1]" },
    border_size = 0,
    rounding    = 0,
})
hl.window_rule({
    name  = "no-gaps-f1",
    match = { float = false, workspace = "f[1]" },
    border_size = 0,
    rounding    = 0,
})

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
        force_split    = 2,    -- new windows always open right/below (Omarchy)
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper    = 0,    -- hyprpaper owns the background; no mascot fallback
        disable_hyprland_logo      = true,
        disable_splash_rendering   = true,
        disable_scale_notification = true,
        focus_on_activate          = true,
        anr_missed_pings           = 3,
        on_focus_under_fullscreen  = 1,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

-- Trackpad gestures (apple-spi-trackpad). 1:1 with the swipe, so they track
-- your fingers rather than firing once.
-- No workspace-overview plugin builds against 0.56.2 (hyprexpo was removed from
-- hyprwm/hyprland-plugins; Hyprspace still pins 0.50.1), so this is a picker
-- over every window on every workspace instead.
local function overview()
    hl.dispatch(hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/windowswitcher.py"))
end

-- 3 fingers sideways: slide between workspaces
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- 3 fingers up/down: fullscreen the window, or reach for the scratchpad
hl.gesture({ fingers = 3, direction = "up",   scale = 1.5, action = "fullscreen" })
hl.gesture({ fingers = 3, direction = "down", action = "special", workspace_name = "scratchpad" })

-- 4 fingers up: workspace overview (needs the hyprexpo plugin)
hl.gesture({ fingers = 4, direction = "up", action = overview })

-- 4-finger pinch: live cursor zoom, anchored where the pinch started.
-- Deliberately 4 fingers, so 2-finger pinch still reaches the browser.
hl.gesture({ fingers = 4, direction = "pinch", action = "cursor_zoom", zoom_level = 1, mode = "live" })

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

-- Omarchy's keymap (github.com/basecamp/omarchy), translated to the Lua config
-- and rewired to the tools actually installed here (no omarchy-* helpers).
-- Layout source: default/hypr/bindings/{tiling-v2,utilities,clipboard,media}.conf
--                config/hypr/bindings.conf

local mainMod  = "SUPER" -- Sets "Windows" key as main modifier
local browser  = "chromium"
local editor   = "kitty -e vim"
local webapp   = "chromium --app="

-- Digit row. Omarchy binds these by keycode (code:10-19) so the layout does not
-- matter; kb_layout here is "us", so the plain keysyms are equivalent and show
-- up properly in `hyprctl binds`.
local digitKeys = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "0" }


-------------------
---- 1. APPS ------
-------------------

hl.bind(mainMod .. " + Return",               hl.dsp.exec_cmd(terminal),     { description = "Terminal" })
hl.bind(mainMod .. " + SHIFT + Return",       hl.dsp.exec_cmd(browser),      { description = "Browser" })
hl.bind(mainMod .. " + SHIFT + B",            hl.dsp.exec_cmd(browser),      { description = "Browser" })
hl.bind(mainMod .. " + SHIFT + ALT + B",      hl.dsp.exec_cmd(browser .. " --incognito"), { description = "Browser (private)" })
hl.bind(mainMod .. " + SHIFT + F",            hl.dsp.exec_cmd(fileManager),  { description = "File manager" })
hl.bind(mainMod .. " + SHIFT + N",            hl.dsp.exec_cmd(editor),       { description = "Editor" })
hl.bind(mainMod .. " + SHIFT + T",            hl.dsp.exec_cmd("kitty --class TUI.float -e sh -c 'command -v btop >/dev/null && btop || htop'"), { description = "Activity monitor" })

-- Web apps (Omarchy runs these as PWAs; chromium --app is the same idea)
hl.bind(mainMod .. " + SHIFT + A",            hl.dsp.exec_cmd(webapp .. "https://chatgpt.com"),        { description = "ChatGPT" })
hl.bind(mainMod .. " + SHIFT + ALT + A",      hl.dsp.exec_cmd(webapp .. "https://grok.com"),           { description = "Grok" })
hl.bind(mainMod .. " + SHIFT + Y",            hl.dsp.exec_cmd(webapp .. "https://youtube.com/"),       { description = "YouTube" })
hl.bind(mainMod .. " + SHIFT + X",            hl.dsp.exec_cmd(webapp .. "https://x.com/"),             { description = "X" })
hl.bind(mainMod .. " + SHIFT + ALT + X",      hl.dsp.exec_cmd(webapp .. "https://x.com/compose/post"), { description = "X post" })
hl.bind(mainMod .. " + SHIFT + ALT + G",      hl.dsp.exec_cmd(webapp .. "https://web.whatsapp.com/"),  { description = "WhatsApp" })
hl.bind(mainMod .. " + SHIFT + CTRL + G",     hl.dsp.exec_cmd(webapp .. "https://messages.google.com/web/conversations"), { description = "Google Messages" })
hl.bind(mainMod .. " + SHIFT + P",            hl.dsp.exec_cmd(webapp .. "https://photos.google.com/"), { description = "Google Photos" })

-- Omarchy also ships: SUPER SHIFT + M music, + O Obsidian, + G Signal, + D lazydocker,
-- + W Typora, + SLASH 1Password, + C/E HEY calendar & mail. Not installed here; add
-- them the same way once the app exists.


---------------------
---- 2. TILING ------
---------------------

hl.bind(mainMod .. " + W", hl.dsp.window.close(), { description = "Close window" })
-- Under a Lua config `hyprctl dispatch` expects Lua, so do this in-process.
hl.bind("CTRL + ALT + Delete", function()
    for _, w in ipairs(hl.get_windows()) do
        hl.dispatch(hl.dsp.window.close({ window = w }))
    end
end, { description = "Close all windows" })

hl.bind(mainMod .. " + J",         hl.dsp.layout("togglesplit"),                          { description = "Toggle window split" })
hl.bind(mainMod .. " + P",         hl.dsp.window.pseudo(),                                { description = "Pseudo window" })
hl.bind(mainMod .. " + T",         hl.dsp.window.float({ action = "toggle" }),            { description = "Toggle window floating/tiling" })
hl.bind(mainMod .. " + F",         hl.dsp.window.fullscreen({ mode = "fullscreen" }),     { description = "Full screen" })
hl.bind(mainMod .. " + CTRL + F",  hl.dsp.window.fullscreen_state({ internal = 0, client = 2 }), { description = "Tiled full screen" })
hl.bind(mainMod .. " + ALT + F",   hl.dsp.window.fullscreen({ mode = "maximized" }),      { description = "Full width" })

-- Pop a window out: float it and pin it above everything
hl.bind(mainMod .. " + O", function()
    hl.dispatch(hl.dsp.window.float({ action = "enable" }))
    hl.dispatch(hl.dsp.window.pin({ action = "enable" }))
    hl.dispatch(hl.dsp.window.bring_to_top())
end, { description = "Pop window out (float & pin)" })

-- Omarchy toggles the layout per workspace; this toggles it globally
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd(
    [[case "$(hyprctl getoption general:layout)" in *dwindle*) hyprctl keyword general:layout master;; *) hyprctl keyword general:layout dwindle;; esac]]),
    { description = "Toggle workspace layout" })

-- Move focus with SUPER + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }),  { description = "Focus on left window" })
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }), { description = "Focus on right window" })
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }),    { description = "Focus on above window" })
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }),  { description = "Focus on below window" })

-- Swap the active window with its neighbour
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.swap({ direction = "left" }),  { description = "Swap window to the left" })
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.swap({ direction = "right" }), { description = "Swap window to the right" })
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.swap({ direction = "up" }),    { description = "Swap window up" })
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.swap({ direction = "down" }),  { description = "Swap window down" })

-- Move the whole workspace to another monitor
hl.bind(mainMod .. " + SHIFT + ALT + left",  hl.dsp.workspace.move({ monitor = "l" }), { description = "Move workspace to left monitor" })
hl.bind(mainMod .. " + SHIFT + ALT + right", hl.dsp.workspace.move({ monitor = "r" }), { description = "Move workspace to right monitor" })
hl.bind(mainMod .. " + SHIFT + ALT + up",    hl.dsp.workspace.move({ monitor = "u" }), { description = "Move workspace to up monitor" })
hl.bind(mainMod .. " + SHIFT + ALT + down",  hl.dsp.workspace.move({ monitor = "d" }), { description = "Move workspace to down monitor" })

-- Workspaces on the digit row: switch, move window, move window silently
for i, key in ipairs(digitKeys) do
    hl.bind(mainMod .. " + " .. key,
        hl.dsp.focus({ workspace = i }),
        { description = "Switch to workspace " .. i })
    hl.bind(mainMod .. " + SHIFT + " .. key,
        hl.dsp.window.move({ workspace = i }),
        { description = "Move window to workspace " .. i })
    hl.bind(mainMod .. " + SHIFT + ALT + " .. key,
        hl.dsp.window.move({ workspace = i, follow = false }),
        { description = "Move window silently to workspace " .. i })
end

-- Scratchpad
hl.bind(mainMod .. " + S",       hl.dsp.workspace.toggle_special("scratchpad"), { description = "Toggle scratchpad" })
hl.bind(mainMod .. " + ALT + S", hl.dsp.window.move({ workspace = "special:scratchpad", follow = false }), { description = "Move window to scratchpad" })

-- TAB between workspaces
hl.bind(mainMod .. " + Tab",           hl.dsp.focus({ workspace = "e+1" }),      { description = "Next workspace" })
hl.bind(mainMod .. " + SHIFT + Tab",   hl.dsp.focus({ workspace = "e-1" }),      { description = "Previous workspace" })
hl.bind(mainMod .. " + CTRL + Tab",    hl.dsp.focus({ workspace = "previous" }), { description = "Former workspace" })

-- Named project workspaces: jump to sub-workspace 1 of each project.
for _, proj in ipairs(projects) do
    local n = proj.name
    hl.bind(mainMod .. " + SHIFT + " .. proj.key,
        hl.dsp.focus({ workspace = "name:" .. n .. ".1" }),
        { description = n .. " workspace" })
end

-- Cycle sub-workspaces within the current project (no-op elsewhere).
hl.bind(mainMod .. " + bracketright", hl.dsp.exec_cmd(wsSub .. " next"), { description = "Next sub-workspace" })
hl.bind(mainMod .. " + bracketleft",  hl.dsp.exec_cmd(wsSub .. " prev"), { description = "Previous sub-workspace" })

-- Jump to whatever has been waiting longest: a pending question first, then a
-- finished command, oldest of each. Repeating it walks the backlog in order.
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("$HOME/.local/bin/ws-attention"),
    { description = "Go to what needs me" })

-- Clickable F1-F12 overlay. This machine has a Touch Bar and no physical
-- function row; the overlay never takes keyboard focus, so the keys it
-- sends land in whatever window is actually focused. Re-run to dismiss.
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/fkeys-overlay.py"), { description = "F-key overlay" })
-- The Touch Bar on screen. Where a real strip exists Fn belongs to it, so the
-- bar answers to a double-tap of Ctrl there and leaves Fn alone; elsewhere
-- there is no conflict and Fn is the trigger. dfrbar-launch decides which,
-- per machine, so this pair is correct everywhere.
-- The Ctrl bind is non-consuming: Ctrl keeps working as a modifier.
hl.bind("XF86Fn", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/dfrbar-launch fn"), { description = "On-screen Touch Bar (Fn)" })
hl.bind("Control_L", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/dfrbar-launch ctrl"), { description = "On-screen Touch Bar (double-tap Ctrl)", non_consuming = true })
hl.bind("Control_R", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/dfrbar-launch ctrl"), { description = "On-screen Touch Bar (double-tap Ctrl)", non_consuming = true })
-- Also sent by the Touch Bar's commit counter, so tapping the figures opens
-- the month behind them.
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/commitheat.py"), { description = "Commits by hour" })
-- Also sent by the Touch Bar's usage buttons, one combo per account, so
-- tapping a set of bars opens everything known about that account. Keep
-- these in step with the Account keys in tiny-dfr.config.toml.
local llmdetail = "$HOME/.config/hypr/scripts/llmdetail.py "
hl.bind(mainMod .. " + SHIFT + U", hl.dsp.exec_cmd(llmdetail .. "you@example.com"),   { description = "Usage: first account" })
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.exec_cmd(llmdetail .. "other@example.com"), { description = "Usage: second account" })
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd(llmdetail .. "codex"),             { description = "Usage: codex" })
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(llmdetail .. "opencode-go"),      { description = "Usage: opencode-go" })

-- Cycle windows on the active workspace
hl.bind("ALT + Tab", function()
    hl.dispatch(hl.dsp.window.cycle_next())
    hl.dispatch(hl.dsp.window.bring_to_top())
end, { description = "Focus on next window" })
hl.bind("ALT + SHIFT + Tab", function()
    hl.dispatch(hl.dsp.window.cycle_next({ next = false }))
    hl.dispatch(hl.dsp.window.bring_to_top())
end, { description = "Focus on previous window" })

-- Cycle monitors
hl.bind("CTRL + ALT + Tab",         hl.dsp.focus({ monitor = "+1" }), { description = "Focus on next monitor" })
hl.bind("CTRL + ALT + SHIFT + Tab", hl.dsp.focus({ monitor = "-1" }), { description = "Focus on previous monitor" })

-- Resize the active window with SUPER + - / =
hl.bind(mainMod .. " + minus",           hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { description = "Expand window left" })
hl.bind(mainMod .. " + equal",           hl.dsp.window.resize({ x = 100,  y = 0, relative = true }), { description = "Shrink window left" })
hl.bind(mainMod .. " + SHIFT + minus",   hl.dsp.window.resize({ x = 0, y = -100, relative = true }), { description = "Shrink window up" })
hl.bind(mainMod .. " + SHIFT + equal",   hl.dsp.window.resize({ x = 0, y = 100,  relative = true }), { description = "Expand window down" })

-- Scroll through workspaces, drag windows with the mouse
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Scroll active workspace forward" })
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }), { description = "Scroll active workspace backward" })
hl.bind(mainMod .. " + mouse:272",  hl.dsp.window.drag(),   { mouse = true, description = "Move window" })
hl.bind(mainMod .. " + mouse:273",  hl.dsp.window.resize(), { mouse = true, description = "Resize window" })


---------------------
---- 3. GROUPS ------
---------------------

hl.bind(mainMod .. " + G",         hl.dsp.group.toggle(),                        { description = "Toggle window grouping" })
hl.bind(mainMod .. " + ALT + G",   hl.dsp.window.move({ out_of_group = true }),  { description = "Move active window out of group" })

hl.bind(mainMod .. " + ALT + left",  hl.dsp.window.move({ into_or_create_group = "left" }),  { description = "Move window to group on left" })
hl.bind(mainMod .. " + ALT + right", hl.dsp.window.move({ into_or_create_group = "right" }), { description = "Move window to group on right" })
hl.bind(mainMod .. " + ALT + up",    hl.dsp.window.move({ into_or_create_group = "up" }),    { description = "Move window to group on top" })
hl.bind(mainMod .. " + ALT + down",  hl.dsp.window.move({ into_or_create_group = "down" }),  { description = "Move window to group on bottom" })

hl.bind(mainMod .. " + ALT + Tab",           hl.dsp.group.next(), { description = "Next window in group" })
hl.bind(mainMod .. " + ALT + SHIFT + Tab",   hl.dsp.group.prev(), { description = "Previous window in group" })
hl.bind(mainMod .. " + CTRL + left",         hl.dsp.group.prev(), { description = "Move grouped window focus left" })
hl.bind(mainMod .. " + CTRL + right",        hl.dsp.group.next(), { description = "Move grouped window focus right" })
hl.bind(mainMod .. " + ALT + mouse_down",    hl.dsp.group.next(), { description = "Next window in group" })
hl.bind(mainMod .. " + ALT + mouse_up",      hl.dsp.group.prev(), { description = "Previous window in group" })

for i = 1, 5 do
    hl.bind(mainMod .. " + ALT + " .. digitKeys[i],
        hl.dsp.group.active({ index = i }),
        { description = "Switch to group window " .. i })
end


------------------------
---- 4. UTILITIES ------
------------------------

-- Menus
hl.bind(mainMod .. " + SPACE",  hl.dsp.exec_cmd(menu), { description = "Launch apps" })
hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/powermenu.sh"), { description = "System menu" })
hl.bind(mainMod .. " + K",      hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/keybinds.sh"), { description = "Show key bindings" })
hl.bind(mainMod .. " + A",      overview, { description = "Find window (all workspaces)" })

-- Aesthetics
hl.bind(mainMod .. " + SHIFT + SPACE",        hl.dsp.exec_cmd("killall -SIGUSR1 waybar"), { description = "Toggle top bar" })
hl.bind(mainMod .. " + CTRL + SPACE",         hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/wallpaper.sh menu"),   { description = "Background menu" })
hl.bind(mainMod .. " + SHIFT + CTRL + SPACE", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/wallpaper.sh random"), { description = "Random background" })

-- Notifications (mako)
hl.bind(mainMod .. " + comma",                 hl.dsp.exec_cmd("makoctl dismiss"),         { description = "Dismiss last notification" })
hl.bind(mainMod .. " + SHIFT + comma",         hl.dsp.exec_cmd("makoctl dismiss --all"),   { description = "Dismiss all notifications" })
hl.bind(mainMod .. " + CTRL + comma",          hl.dsp.exec_cmd("makoctl mode -t do-not-disturb && notify-send 'Notifications' \"$(makoctl mode)\""), { description = "Toggle silencing notifications" })
hl.bind(mainMod .. " + ALT + comma",           hl.dsp.exec_cmd("makoctl invoke"),          { description = "Invoke last notification" })
hl.bind(mainMod .. " + SHIFT + ALT + comma",   hl.dsp.exec_cmd("makoctl restore"),         { description = "Restore last notification" })

-- Toggles
hl.bind(mainMod .. " + CTRL + I", hl.dsp.exec_cmd("pkill hypridle && notify-send 'Idle lock off' || (hypridle & notify-send 'Idle lock on')"), { description = "Toggle locking on idle" })
hl.bind(mainMod .. " + CTRL + N", hl.dsp.exec_cmd("pkill hyprsunset && notify-send 'Nightlight off' || (hyprsunset -t 4000 & notify-send 'Nightlight on')"), { description = "Toggle nightlight" })

-- Captures (grim + slurp; Omarchy uses its own capture helpers)
local shotdir = "$HOME/Pictures/Screenshots"
hl.bind("Print", hl.dsp.exec_cmd(
    "mkdir -p " .. shotdir .. " && grim -g \"$(slurp)\" - | tee " ..
    shotdir .. "/$(date +%Y-%m-%d_%H-%M-%S).png | wl-copy && notify-send 'Screenshot' 'Region copied to clipboard'"),
    { description = "Screenshot (region)" })
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(
    "mkdir -p " .. shotdir .. " && grim - | tee " ..
    shotdir .. "/$(date +%Y-%m-%d_%H-%M-%S).png | wl-copy && notify-send 'Screenshot' 'Screen copied to clipboard'"),
    { description = "Screenshot (whole screen)" })
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("pkill hyprpicker || hyprpicker -a"), { description = "Color picker" })

-- Waybar-less information
hl.bind(mainMod .. " + CTRL + ALT + T", hl.dsp.exec_cmd([[notify-send -u low "$(date +"%A %H:%M  ·  %d %B %Y  ·  Week %V")"]]), { description = "Show time" })
hl.bind(mainMod .. " + CTRL + ALT + B", hl.dsp.exec_cmd(
    [[notify-send -u low "Battery $(cat /sys/class/power_supply/macsmc-battery/capacity)% ($(cat /sys/class/power_supply/macsmc-battery/status))"]]),
    { description = "Show battery remaining" })

-- Zoom
hl.bind(mainMod .. " + CTRL + Z", hl.dsp.exec_cmd(
    [[hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk '/float/ {print $2 + 1; exit}')"]]),
    { description = "Zoom in" })
hl.bind(mainMod .. " + CTRL + ALT + Z", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1"), { description = "Reset zoom" })

-- Control panels (Omarchy's; these are TUIs, install them to light the binds up)
hl.bind(mainMod .. " + CTRL + A", hl.dsp.exec_cmd("command -v wiremix >/dev/null && kitty --class TUI.float -e wiremix || notify-send 'wiremix not installed' 'sudo pacman -S wiremix'"), { description = "Audio controls" })
hl.bind(mainMod .. " + CTRL + B", hl.dsp.exec_cmd("command -v bluetui >/dev/null && kitty --class TUI.float -e bluetui || notify-send 'bluetui not installed' 'sudo pacman -S bluetui'"), { description = "Bluetooth controls" })
hl.bind(mainMod .. " + CTRL + W", hl.dsp.exec_cmd("command -v impala >/dev/null && kitty --class TUI.float -e impala || notify-send 'impala not installed' 'sudo pacman -S impala'"), { description = "Wifi controls" })

-- Lock system
hl.bind(mainMod .. " + CTRL + L", hl.dsp.exec_cmd("loginctl lock-session"), { description = "Lock system" })

-- Reload waybar (not an Omarchy bind; kept from the previous config)
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("killall -SIGUSR2 waybar"), { description = "Reload waybar" })

-- Omarchy binds with no local equivalent installed, left out on purpose:
--   SUPER CTRL + E emoji picker (walker), SUPER CTRL + C capture menu,
--   SUPER ALT + SPACE / CTRL + O / CTRL + H omarchy menus, SUPER CTRL + SPACE themes,
--   SUPER BACKSPACE transparency/gaps toggles, SUPER CTRL + A/B/W audio-bt-wifi TUIs,
--   SUPER CTRL + S share, SUPER CTRL + R reminders, SUPER CTRL + X dictation,
--   ALT + PRINT screen recording, SUPER CTRL + PRINT OCR, SUPER + / monitor scaling.


------------------------
---- 5. CLIPBOARD ------
------------------------

-- Universal copy/paste/cut: Omarchy sends the terminal-safe combos to the app
hl.bind(mainMod .. " + C", hl.dsp.send_shortcut({ mods = "CTRL",  key = "Insert" }), { description = "Universal copy" })
hl.bind(mainMod .. " + V", hl.dsp.send_shortcut({ mods = "SHIFT", key = "Insert" }), { description = "Universal paste" })
hl.bind(mainMod .. " + X", hl.dsp.send_shortcut({ mods = "CTRL",  key = "X" }),      { description = "Universal cut" })
hl.bind(mainMod .. " + CTRL + V", hl.dsp.exec_cmd(
    "cliphist list | hyprlauncher --dmenu | cliphist decode | wl-copy"),
    { description = "Clipboard manager" })


--------------------
---- 6. MEDIA ------
--------------------

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("command -v swayosd-client >/dev/null && swayosd-client --output-volume raise || wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true, description = "Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("command -v swayosd-client >/dev/null && swayosd-client --output-volume lower || wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true, description = "Volume down" })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("command -v swayosd-client >/dev/null && swayosd-client --output-volume mute-toggle || wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, description = "Mute" })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("command -v swayosd-client >/dev/null && swayosd-client --input-volume mute-toggle || wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, description = "Mute microphone" })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("command -v swayosd-client >/dev/null && swayosd-client --brightness raise || brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true, description = "Brightness up" })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("command -v swayosd-client >/dev/null && swayosd-client --brightness lower || brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true, description = "Brightness down" })

-- Precise 1% steps with ALT, min/max with SHIFT (Omarchy)
hl.bind("ALT + XF86AudioRaiseVolume",   hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+"), { locked = true, repeating = true, description = "Volume up precise" })
hl.bind("ALT + XF86AudioLowerVolume",   hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"),      { locked = true, repeating = true, description = "Volume down precise" })
hl.bind("ALT + XF86MonBrightnessUp",    hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 1%+"),                  { locked = true, repeating = true, description = "Brightness up precise" })
hl.bind("ALT + XF86MonBrightnessDown",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 1%-"),                  { locked = true, repeating = true, description = "Brightness down precise" })
hl.bind("SHIFT + XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 100%"),                 { locked = true, description = "Brightness maximum" })
hl.bind("SHIFT + XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 1%"),                   { locked = true, description = "Brightness minimum" })

-- Keyboard backlight
hl.bind("XF86KbdBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -c leds -d kbd_backlight set 10%+"), { locked = true, repeating = true, description = "Keyboard brightness up" })
hl.bind("XF86KbdBrightnessDown", hl.dsp.exec_cmd("brightnessctl -c leds -d kbd_backlight set 10%-"), { locked = true, repeating = true, description = "Keyboard brightness down" })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("command -v swayosd-client >/dev/null && swayosd-client --playerctl next || playerctl next"),       { locked = true, description = "Next track" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("command -v swayosd-client >/dev/null && swayosd-client --playerctl play-pause || playerctl play-pause"), { locked = true, description = "Pause" })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("command -v swayosd-client >/dev/null && swayosd-client --playerctl play-pause || playerctl play-pause"), { locked = true, description = "Play" })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("command -v swayosd-client >/dev/null && swayosd-client --playerctl previous || playerctl previous"),   { locked = true, description = "Previous track" })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})


------------------------------------------------
---- OMARCHY WINDOW RULES (default/hypr/*) ------
------------------------------------------------

-- Everything gets the default-opacity tag; the app rules below opt out of it,
-- and the very last rule applies the opacity to whatever still carries it.
hl.window_rule({ name = "tag-default-opacity", match = { class = ".*" }, tag = "+default-opacity" })

-- Terminals: Hyprland keeps them nearly opaque; the see-through part is
-- kitty's own background_opacity, which keeps the text crisp.
hl.window_rule({ name = "tag-terminal",  match = { class = "(Alacritty|kitty|com.mitchellh.ghostty|foot)" }, tag = "+terminal" })
hl.window_rule({ name = "terminal-untag", match = { tag = "terminal" }, tag = "-default-opacity" })
hl.window_rule({ name = "terminal-opacity", match = { tag = "terminal" }, opacity = "0.985 0.96" })

-- Browsers: only a hint of fade when unfocused
hl.window_rule({ name = "tag-chromium", match = { class = "((google-)?[cC]hrom(e|ium)|[bB]rave-browser|[mM]icrosoft-edge|Vivaldi-stable|helium)" }, tag = "+chromium-based-browser" })
hl.window_rule({ name = "tag-firefox",  match = { class = "([fF]irefox|zen|librewolf)" }, tag = "+firefox-based-browser" })
hl.window_rule({ name = "chromium-untag", match = { tag = "chromium-based-browser" }, tag = "-default-opacity" })
hl.window_rule({ name = "firefox-untag",  match = { tag = "firefox-based-browser" },  tag = "-default-opacity" })
-- Chromium --app windows misbehave unless forced to tile
hl.window_rule({ name = "chromium-tile",    match = { tag = "chromium-based-browser" }, tile = true })
hl.window_rule({ name = "chromium-opacity", match = { tag = "chromium-based-browser" }, opacity = "1.0 0.985" })
hl.window_rule({ name = "firefox-opacity",  match = { tag = "firefox-based-browser" },  opacity = "1.0 0.985" })
-- The "... is sharing your screen" bar has a broken Hide button on Wayland
hl.window_rule({ name = "hide-sharing-bar", match = { title = ".*is sharing.*" }, workspace = "special silent" })

-- Picture-in-picture: floating, pinned, bottom-right, no border, never faded
hl.window_rule({ name = "tag-pip",     match = { title = "(Picture.?in.?[Pp]icture)" }, tag = "+pip" })
hl.window_rule({ name = "pip-untag",   match = { tag = "pip" }, tag = "-default-opacity" })
hl.window_rule({ name = "pip-float",   match = { tag = "pip" }, float = true })
hl.window_rule({ name = "pip-pin",     match = { tag = "pip" }, pin = true })
hl.window_rule({ name = "pip-size",    match = { tag = "pip" }, size = "600 338" })
hl.window_rule({ name = "pip-aspect",  match = { tag = "pip" }, keep_aspect_ratio = true })
hl.window_rule({ name = "pip-border",  match = { tag = "pip" }, border_size = 0 })
hl.window_rule({ name = "pip-opacity", match = { tag = "pip" }, opacity = "1 1" })
hl.window_rule({ name = "pip-place",   match = { tag = "pip" }, move = "monitor_w-window_w-40 monitor_h*0.04" })

-- Utility windows that should float centred instead of tiling
hl.window_rule({ name = "tag-floating-window", match = { class = "(TUI.float|org.gnome.Calculator|org.gnome.Evince|com.gabm.satty|imv|mpv|blueman-manager|nm-connection-editor|org.pulseaudio.pavucontrol|pavucontrol)" }, tag = "+floating-window" })
hl.window_rule({ name = "floating-window-float",  match = { tag = "floating-window" }, float = true })
hl.window_rule({ name = "floating-window-center", match = { tag = "floating-window" }, center = true })
hl.window_rule({ name = "floating-window-size",   match = { tag = "floating-window" }, size = "875 600" })

-- File pickers and save dialogs
hl.window_rule({
    name  = "float-file-dialogs",
    match = {
        class = "(xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus|org.kde.dolphin)",
        title = "^(Open.*Files?|Open [Ff]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[Cc]hoose.*)",
    },
    tag = "+floating-window",
})

-- Media windows stay fully opaque
hl.window_rule({ name = "media-untag",   match = { class = "^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|imv)$" }, tag = "-default-opacity" })
hl.window_rule({ name = "media-opacity", match = { class = "^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|imv)$" }, opacity = "1 1" })

-- Popped-out windows (SUPER + O) get softer corners
hl.window_rule({ name = "pop-rounding", match = { tag = "pop" }, rounding = 8 })

-- Applied last, to every window that did not opt out above
hl.window_rule({ name = "default-opacity", match = { tag = "default-opacity" }, opacity = "0.985 0.96" })

-- The launcher should not animate in
hl.layer_rule({ name = "no-anim-launcher", match = { namespace = "^hyprlauncher$" }, no_anim = true })


-----------------------
------ PLUGINS --------
-----------------------

-- hyprbars: title bars, styled to match the Catppuccin theme.
-- Guarded, because plugins must be rebuilt after every Hyprland update
-- (`hyprpm update`) and are simply absent until then.
if hl.plugin.hyprbars ~= nil then
    hl.config({
        plugin = {
            hyprbars = {
                bar_height        = 20,
                bar_color         = "rgba(1e1e2eee)",
                ["col.text"]      = "rgb(cdd6f4)",
                bar_text_font     = "JetBrainsMono Nerd Font",
                bar_text_size     = 10,
                bar_text_weight   = "medium",
                bar_text_align    = "left",
                bar_padding       = 10,
                bar_button_padding = 6,
                bar_buttons_alignment = "right",
                bar_blur          = true,
                bar_part_of_window = true,
                icon_on_hover     = true,
                inactive_button_color = "rgb(585b70)",
                on_double_click   = [[hyprctl dispatch 'hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" })']],
            },
        },
    })

    -- Buttons are laid out right to left from the aligned edge.
    hl.plugin.hyprbars.add_button({
        bg_color = "rgb(f38ba8)", fg_color = "rgb(1e1e2e)", size = 11, icon = "",
        action = "hyprctl dispatch 'hl.dsp.window.close()'",
    })
    hl.plugin.hyprbars.add_button({
        bg_color = "rgb(f9e2af)", fg_color = "rgb(1e1e2e)", size = 11, icon = "",
        action = [[hyprctl dispatch 'hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" })']],
    })
    hl.plugin.hyprbars.add_button({
        bg_color = "rgb(a6e3a1)", fg_color = "rgb(1e1e2e)", size = 11, icon = "",
        action = "hyprctl dispatch 'hl.dsp.window.float({ action = \"toggle\" })'",
    })

    -- Tiled windows keep every pixel: a 20px bar per window is a real cost in a
    -- tiling layout, and the groupbar already labels grouped windows.
    -- Delete this rule to get bars on everything.
    hl.window_rule({
        name  = "no-bar-on-tiled",
        match = { float = false },
        ["hyprbars:no_bar"] = true,
    })
end

-----------------------------
---- CHEATSHEET WINDOW ------
-----------------------------

hl.window_rule({
    name  = "float-keybind-cheatsheet",
    match = { class = "^hypr-keybinds$" },

    float = true,
    size  = "900 780",
    center = true,
})

